CREATE TABLE TB_ALUNO (
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF CHAR(11) NOT NULL,
	MATRICULA BIGINT(20) NOT NULL,
	DATA_ANIVERSARIO DATE
);

CREATE TABLE TB_PROFESSOR (
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF CHAR(11) NOT NULL,
	SALARIO DECIMAL(10,2)
);